# fly.toml app configuration file generated for joaco-receipt-bot on 2026-08-18T15:46:44-03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'joaco-receipt-bot'
primary_region = 'gru'

[build]
  dockerfile = './Dockerfile'

[deploy]
  release_command = 'node dist/src/db/migrate.js'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
